import Course.CourseLib
import Course.L01_Intro
import Course.L02_BasicProofs
import Course.L03_Sorting
import Course.L04_SortingDeux
import Course.L05_ComprehensiveRecap
import Course.L06_FP_Primer
import Course.L07_TermsAsProofs
import Course.L08_ExpLang
import Course.L09_DFA
import Course.L10_DependentTypes
import Course.L11_DFA_Redux
import Course.L12_DExpLang
import Course.L13_ComprehensiveRecap
import Course.L14_AdvancedTactics
import Course.L15_Universes
import Course.L16_RecursionInduction
import Course.L17_Parsing
import Course.L18_ProofAdvice
import Course.Examples.L14_Ex_DFA
import Course.Examples.L14_Ex_ExpLang
import Course.Examples.L14_Ex_Sorting
import Course.Examples.L18_Ex_DExp
import Course.Examples.L18_Ex_Dfa
